// <auto-generated />
using System;
using DigiCard.Modules.Templates;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiCard.Modules.Templates.Infrastructure.Migrations
{
    [DbContext(typeof(TemplatesDbContext))]
    [Migration("20260915210511_RemoveTermehTemplate")]
    partial class RemoveTermehTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("templates")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiCard.Modules.Templates.CardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Artwork")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ink")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Ornament")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SafeBottom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(75);

                    b.Property<int>("SafeTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Typeface")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Templates", "templates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0103"),
                            Accent = "#847b57",
                            Artwork = "sepid-sade",
                            Background = "linear-gradient(180deg,#fffdf9 0%,#f6f1e8 100%)",
                            Category = "wedding",
                            Family = "minimal",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "سپید ساده",
                            Ornament = "rule",
                            SafeBottom = 80,
                            SafeTop = 44,
                            Slug = "sepid-sade",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0104"),
                            Accent = "#7c764f",
                            Artwork = "khat-e-noor",
                            Background = "#fbfaf7",
                            Category = "aghd",
                            Family = "minimal",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "خط نور",
                            Ornament = "dot",
                            SafeBottom = 58,
                            SafeTop = 22,
                            Slug = "khat-e-noor",
                            Typeface = "display",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0105"),
                            Accent = "#807547",
                            Artwork = "sadegi-talaei",
                            Background = "linear-gradient(180deg,#fdfbf6 0%,#f4ecdd 100%)",
                            Category = "anniversary",
                            Family = "minimal",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "سادگی طلایی",
                            Ornament = "rule",
                            SafeBottom = 58,
                            SafeTop = 22,
                            Slug = "sadegi-talaei",
                            Typeface = "display",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0106"),
                            Accent = "#c17f8f",
                            Artwork = "golab-abrang",
                            Background = "radial-gradient(120% 80% at 50% 0%,#fdeef1 0%,#fbf7f4 55%,#f7eee9 100%)",
                            Category = "wedding",
                            Family = "watercolor",
                            Frame = "none",
                            Ink = "#4a3a3e",
                            Layout = "centered",
                            Name = "گلاب آبرنگ",
                            Ornament = "floral",
                            SafeBottom = 67,
                            SafeTop = 37,
                            Slug = "golab-abrang",
                            Typeface = "serif",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0107"),
                            Accent = "#85785d",
                            Artwork = "shaghayegh",
                            Background = "radial-gradient(100% 70% at 20% 10%,#fdeceb 0%,#fcf8f5 60%,#f8f1ec 100%)",
                            Category = "engagement",
                            Family = "watercolor",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "شقایق",
                            Ornament = "floral",
                            SafeBottom = 76,
                            SafeTop = 40,
                            Slug = "shaghayegh",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0108"),
                            Accent = "#6d5c7f",
                            Artwork = "banafsheh",
                            Background = "radial-gradient(110% 80% at 80% 0%,#f1edfa 0%,#faf8fc 55%,#f4f1f7 100%)",
                            Category = "baleboron",
                            Family = "watercolor",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "بنفشه",
                            Ornament = "floral",
                            SafeBottom = 81,
                            SafeTop = 45,
                            Slug = "banafsheh",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0109"),
                            Accent = "#80673d",
                            Artwork = "hana-o-gol",
                            Background = "linear-gradient(160deg,#fdf4e4 0%,#fbf6ee 55%,#f6ead6 100%)",
                            Category = "hanabandan",
                            Family = "watercolor",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "حنا و گل",
                            Ornament = "floral",
                            SafeBottom = 50,
                            SafeTop = 14,
                            Slug = "hana-o-gol",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0101"),
                            Accent = "#918063",
                            Artwork = "bagh-e-irani",
                            Background = "linear-gradient(180deg,#f4f7f3 0%,#e9f0ea 100%)",
                            Category = "wedding",
                            Family = "persian",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "باغ ایرانی",
                            Ornament = "paisley",
                            SafeBottom = 67,
                            SafeTop = 31,
                            Slug = "bagh-e-irani",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b010b"),
                            Accent = "#566c84",
                            Artwork = "kashi-firouzeh",
                            Background = "linear-gradient(180deg,#eff7f8 0%,#e2eff1 100%)",
                            Category = "hanabandan",
                            Family = "persian",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "کاشی فیروزه",
                            Ornament = "geometric",
                            SafeBottom = 70,
                            SafeTop = 34,
                            Slug = "kashi-firouzeh",
                            Typeface = "display",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0102"),
                            Accent = "#8a7c5c",
                            Artwork = "roz-o-morvarid",
                            Background = "linear-gradient(180deg,#fbf4f6 0%,#f2e6ea 100%)",
                            Category = "wedding",
                            Family = "photo",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "رز و مروارید",
                            Ornament = "dot",
                            SafeBottom = 62,
                            SafeTop = 26,
                            Slug = "roz-o-morvarid",
                            Typeface = "serif",
                            Version = 2
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b010c"),
                            Accent = "#7d6143",
                            Artwork = "ghab-e-khatereh",
                            Background = "linear-gradient(180deg,#f6f7f9 0%,#e9ebef 100%)",
                            Category = "anniversary",
                            Family = "photo",
                            Frame = "none",
                            Ink = "#3c3a36",
                            Layout = "centered",
                            Name = "قاب خاطره",
                            Ornament = "rule",
                            SafeBottom = 69,
                            SafeTop = 33,
                            Slug = "ghab-e-khatereh",
                            Typeface = "serif",
                            Version = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
