// <auto-generated />
using System;
using DigiCard.Modules.Templates;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiCard.Modules.Templates.Infrastructure.Migrations
{
    [DbContext(typeof(TemplatesDbContext))]
    [Migration("20260912220743_InitialTemplates")]
    partial class InitialTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("templates")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiCard.Modules.Templates.CardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Templates", "templates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0101"),
                            Accent = "#52796f",
                            Name = "باغ ایرانی",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a41a6319-3438-4ef9-89da-fae6b30b0102"),
                            Accent = "#a56b7d",
                            Name = "رز و مروارید",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
